name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hostinger_vps 
    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_PRIVATE_SSH }}

      # 3️⃣ Deploy sur VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{secrets.VPS_PORT}} ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "
            cd /home/dev/icanhelp_backend/icanhelp &&
            git pull origin main &&
            docker compose down &&
            docker compose pull &&
            docker compose up -d --build
            docker ps
          "
